version: 2
jobs:
  build:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - run:
          name: Install build dependencies
          command: |
            apt-get update
            apt-get install -y --no-install-recommends --quiet build-essential libopenblas-dev

      - restore_cache:
          keys:
            - pip3.6--{{ checksum ".circleci/config.yml" }}--{{ checksum "setup.py" }}
            - pip3.6

      - run:
          name: Install library
          command: |

            pip install --progress-bar off numpy
            pip install --progress-bar off -e .[test,pytorch]


      - save_cache:
          key: pip3.6--{{ checksum ".circleci/config.yml" }}--{{ checksum "setup.py" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Run tests
          environment:
            OPENBLAS_NUM_THREADS: 2
            OMP_NUM_THREADS: 2
            MKL_NUM_THREADS: 2
          command: |
            bash scripts/test_code.sh

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - build

